### PR TITLE
Create a dataset where the release_date is a numeric timestamp

### PR DESCRIPTION
**Pull request by bidoubiwa**
```bash
cat movies.json | jq '.[]' |jq -c 'try (.release_date |= if . == null or . == "" then . else (. | strptime("%Y-%m-%d") | mktime )  end) catch (.)'  >> movies_ranged.json
```

Added `-c` for minify version.
Since try and catch doesnt work on mapping function I had to append a file with each object.
Because of that, the final file is not formatted well.
Missing wrapping '`[]`' around all objects.
Missing comas after each object.
vim command to add a comma at the end of each object `'%s/}/},/g'`

### CODE REVIEW

**Comment by Kerollmops** [comment]
Can you please replace the current dataset instead of adding a new one ? please.

**Comment by bidoubiwa** [comment]
It's done

**Comment by Kerollmops** [comment]
Why do this new dataset have 6 times more lines than the old one ?

**Comment by bidoubiwa** [comment]
`cat movies.json | jq '.[]' |jq -c 'try (.release_date |= if . == null or . == "" then . else (. | strptime("%Y-%m-%d") | mktime )  end) catch (.)'  >> movies_ranged.json`

Added `-c` for minify version.
Since try and catch doesnt work on mapping function I had to append a file with each object.
Because of that, the final file is not formatted well.
Missing wrapping '`[]`' around all objects.
Missing comas after each object.
vim command to add a comma at the end of each object `'%s/}/},/g'`

**Pull request merged**
